# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller spec for JewishGenealogySearch — driven by build_installer.ps1.

Bundles the launcher, EVERY gui/*.py window + every *_scraper.py, the config/ and
storage/ (and models/) assets, and the Playwright Python package.

The launcher opens windows by importlib from config/sites.json, so PyInstaller cannot
see them by following imports — we therefore add every gui module and every scraper as
a hidden import (auto-discovered below, so new databases are picked up automatically).

NOTE: PyInstaller does NOT bundle the Playwright *browser* binaries — build_installer.ps1
copies the Chromium folder next to the .exe (dist/JewishGenealogySearch/ms-playwright) and the
app points PLAYWRIGHT_BROWSERS_PATH at it on startup.
"""
import os
import glob
from PyInstaller.utils.hooks import collect_all

# Project root = the parent of this spec's folder (the spec lives in packaging/). PyInstaller
# resolves the Analysis script relative to the SPEC dir, so ALL paths here must be absolute,
# anchored to ROOT — otherwise it looks for packaging/JewishGenealogySearch.py and fails.
try:
    ROOT = os.path.dirname(os.path.abspath(SPECPATH))      # SPECPATH = …/packaging
except NameError:
    ROOT = os.path.abspath(os.getcwd())
_p = lambda *a: os.path.join(ROOT, *a)

# ── data folders shipped next to the exe ─────────────────────────────────────
datas = [(_p("config"), "config"), (_p("storage"), "storage")]
if os.path.isdir(_p("models")):
    datas.append((_p("models"), "models"))

# ── hidden imports: every GUI window + every scraper (dynamic import targets) ──
hidden = ["PySide6.QtSvg", "PySide6.QtSvgWidgets"]
for f in glob.glob(_p("gui", "*.py")):
    base = os.path.splitext(os.path.basename(f))[0]
    if base != "__init__":
        hidden.append("gui." + base)
for f in glob.glob(_p("*.py")):
    base = os.path.splitext(os.path.basename(f))[0]
    if base.endswith("_scraper") or base in ("docx_util", "unified_search",
                                             "mh_add_english", "paths_util", "browser_util"):
        hidden.append(base)

# ── Playwright python package (browser binaries handled by the build script) ──
pw_datas, pw_bins, pw_hidden = collect_all("playwright")
hidden += pw_hidden

a = Analysis(
    [_p("JewishGenealogySearch.py")],
    pathex=[ROOT],
    binaries=pw_bins,
    datas=datas + pw_datas,
    hiddenimports=hidden,
    hookspath=[],
    runtime_hooks=[],
    excludes=["tkinter"],
    noarchive=False,
)
pyz = PYZ(a.pure)

# icon / version are generated by build_installer.ps1; fall back gracefully if absent
_icon = _p("config", "app_icon.ico")
_ver  = _p("packaging", "version_info.txt")
exe = EXE(
    pyz, a.scripts, [],
    exclude_binaries=True,
    name="JewishGenealogySearch",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,                       # UPX packing trips antivirus heuristics → keep OFF
    console=False,                   # GUI app → no console window
    icon=_icon if os.path.exists(_icon) else None,
    version=_ver if os.path.exists(_ver) else None,
)
coll = COLLECT(
    exe, a.binaries, a.datas,
    strip=False, upx=False,
    name="JewishGenealogySearch",
)
